# Generated by Django 4.2.20 on 2025-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('regNo', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ranking', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/profileImages')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='ADB', max_length=256),
        ),
    ]
