# Generated by Django 4.2.20 on 2025-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_task_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.CharField(max_length=256),
        ),
    ]
