# Generated by Django 4.2.20 on 2025-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_alter_studentprofile_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(upload_to='student_photos'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(max_length=256),
        ),
    ]
