# Generated by Django 4.2.20 on 2025-04-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_alter_studentprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
