# Generated by Django 4.2.20 on 2025-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0012_alter_studentprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
