# Generated by Django 4.2.20 on 2025-04-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0014_alter_studentprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
