# Generated by Django 4.2.20 on 2025-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0015_alter_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ranking',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
