# Generated by Django 4.2.20 on 2025-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0016_alter_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unit_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20),
        ),
    ]
