# Generated by Django 4.2.20 on 2025-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0017_attendance_unit_name_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=20),
        ),
    ]
