# Generated by Django 4.2.20 on 2025-04-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0018_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='unit_name',
        ),
    ]
