# Generated by Django 4.2.20 on 2025-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0019_remove_attendance_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
